### ISSUE TITLE
Unresponsive search field on mobile [Android 5.0, Chrome 41.0.2272.96]

### ISSUE THREAD

**Issue by kyleoshaughnessy** [ahoskins/Winston#28]
When searching for classes text will not flow into the field until the search results have been generated. This is not an issues when testing from a desktop's browser, i'm unsure of how this would behave in IOS Safari. Maybe we can get a list of different experiences and platform in the comments below. 
![screenshot_2015-03-26-20-16-22](https://cloud.githubusercontent.com/assets/5834110/6861185/999be786-d3f7-11e4-8347-07bdbfbda157.png)

**Comment by ahoskins** [comment]
The accordion is as lazy as possible (it doesn't render courses in the DOM that aren't currently showed).  For now, we will close this, but in the future we may try to further improve this. 

Listviews are so fast on native platforms like Android and iOS is because tons of optimizations and recycling of views is done (this like the ViewHolder pattern - lots of smart tricks like this).  There are Javascript implementations that try to make really speedy ListViews. Like react's [fixed data table](https://github.com/facebook/fixed-data-table)

**Comment by rosshamish** [comment]
So @ahoskins this is feasible?

**Comment by ahoskins** [comment]
Well, the way I understand it, your basically sacrifice speed for versatility.  Our accordion is triple nested and expandable on click.  So I'm not sure it is feasible.  But the fact, there are smart implementations that make big sets of data faster - and these are available for JS also.
